name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn joblib huggingface_hub

      - name: Train and save model
        run: python model.py

      - name: Deploy to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "from huggingface_hub import HfApi; api = HfApi(token='${{ secrets.HF_TOKEN }}'); api.upload_file(path_or_fileobj='model.joblib', path_in_repo='model.joblib', repo_id='DavidNgoue/modele_sn_git_github', repo_type='model'); api.upload_file(path_or_fileobj='model.py', path_in_repo='model.py', repo_id='your-username/ia-model-repo', repo_type='model'); api.upload_file(path_or_fileobj='README.md', path_in_repo='README.md', repo_id='your-username/ia-model-repo', repo_type='model')"

  notify:
    needs: deploy
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Déploiement réussi - ${{ github.repository }}"
          body: | # Utilisez un bloc de style littéral pour un corps de mail multi-lignes plus lisible
            Projet : ${{ github.repository }}
            URL GitHub : ${{ github.server_url }}/${{ github.repository }}
            Commit : ${{ github.sha }}
            Lien Hugging Face : https://huggingface.co/DavidNgoue/modele_sn_git_github
          to: ngouedavidrogeryannick@gmail.com